apiVersion: v1
kind: ConfigMap
metadata:
  name: env-fear-get-data
  namespace: production
data:
  PORT: '3000'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configs-fear-get-data
  namespace: production
data:
  mysqlConfig.js: |-
    const MYSQL_CONFIG = {
      host           : 'fear-mysql',
      user           : 'fear',
      password       : 'youR3allyNeedToChangeThisValue',
      database       : 'fear',
      connectTimeout : 60000,
    }

    module.exports = MYSQL_CONFIG
