apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fear-get-data
    app.kubernetes.io/instance: all
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: back
    app.kubernetes.io/part-of: fear-data
    app.kubernetes.io/managed-by: kubectl
  name: fear-get-data
spec:
  ports:
    - name: get-data
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: fear-get-data
