version: '3'
services:
    get-data:
        image: micro-get-data
        ports:
            - "3000:3000"
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure