apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fear-mysql
    app.kubernetes.io/instance: all
    app.kubernetes.io/version: '5.7'
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: fear-data
    app.kubernetes.io/managed-by: kubectl
  name: fear-mysql
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: fear-mysql
