apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fear-mysql
spec:
  replicas: 1
  serviceName: fear-mysql
  selector:
    matchLabels:
      app.kubernetes.io/name: fear-mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fear-mysql
        app.kubernetes.io/instance: all
        app.kubernetes.io/version: '5.7'
        app.kubernetes.io/component: data
        app.kubernetes.io/part-of: fear-data
        app.kubernetes.io/managed-by: kubectl
      name: fear-mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          envFrom:
            - configMapRef:
                name: env-fear-database
      restartPolicy: Always
